<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Berkas_pekerjaan_model extends CI_Model
{

    public $table = 'berkas_pekerjaan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get a row by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get a row by defined field
    function get_by($fieldkey, $val)
    {
        $this->db->where($fieldkey, $val);
        return $this->db->get($this->table)->row();
    }

    // get data by defined field
    function get_data_by($fieldkey, $val)
    {
        $this->db->where($fieldkey, $val);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        if($q!=NULL){
            $this->db->group_start();
            $this->db->like('id', $q);
            $this->db->or_like('posisi_jabatan', $q);
            $this->db->or_like('kode_bahan', $q);
            $this->db->or_like('nama', $q);
            $this->db->or_like('tipe', $q);
            $this->db->group_end();
        }
        $this->db->from($this->table."_overview");
        return $this->db->count_all_results();
    }
    
    // get total rows
    function total_rows_pekerjaan($idp, $q = NULL) {
        $this->db->group_start();
        $this->db->where('id_pekerjaan', $idp);
        $this->db->group_end();        
        if($q!=NULL){
            $this->db->group_start();
            $this->db->like('id', $q);
            $this->db->or_like('posisi_jabatan', $q);
            $this->db->or_like('kode_bahan', $q);
            $this->db->or_like('nama', $q);
            $this->db->or_like('tipe', $q);
            $this->db->group_end();
        }
        $this->db->from($this->table."_overview");
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        if($q!=NULL){
            $this->db->group_start();
            $this->db->like('id', $q);
            $this->db->or_like('posisi_jabatan', $q);
            $this->db->or_like('kode_bahan', $q);
            $this->db->or_like('nama', $q);
            $this->db->or_like('tipe', $q);
            $this->db->group_end();
        }
        $this->db->order_by("id_pekerjaan", "DESC");
        $this->db->limit($limit, $start);
        return $this->db->get($this->table."_overview")->result();
    }

    // get data with limit and search
    function get_limit_data_pekerjaan($idp, $limit, $start = 0, $q = NULL) {
        $this->db->group_start();
        $this->db->where('id_pekerjaan', $idp);
        $this->db->group_end();        
        if($q!=NULL){
            $this->db->group_start();
            $this->db->like('id', $q);
            $this->db->or_like('posisi_jabatan', $q);
            $this->db->or_like('kode_bahan', $q);
            $this->db->or_like('nama', $q);
            $this->db->or_like('tipe', $q);
            $this->db->group_end();
        }
        $this->db->order_by("id_pekerjaan", "DESC");
        $this->db->limit($limit, $start);
        return $this->db->get($this->table."_overview")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data by spesific field
    function update_by($field, $val, $data)
    {
        $this->db->where($field, $val);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete data by spesific field
    function delete_by($field, $val)
    {
        $this->db->where($field, $val);
        $this->db->delete($this->table);
    }

}

/* End of file Berkas_pekerjaan_model.php */
/* Location: ./application/models/Berkas_pekerjaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-14 06:43:01 */
/* http://harviacode.com */