<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pekerjaan_model extends CI_Model
{

    public $table = 'pekerjaan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get a row by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get a row by defined field
    function get_by($fieldkey, $val)
    {
        $this->db->where($fieldkey, $val);
        return $this->db->get($this->table)->row();
    }

    // get a row by defined field
    function get_pelamar_by($fieldkey, $val)
    {
        $this->db->where($fieldkey, $val);
        $this->db->where("tersedia", "1");
        return $this->db->get($this->table)->row();
    }

    // get data by defined field
    function get_data_by($fieldkey, $val)
    {
        $this->db->where($fieldkey, $val);
        return $this->db->get($this->table)->result();
    }
    
    function get_total_tersedia() {
        $this->db->where("tersedia", "1");
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    
    function get_pekerjaan() {
        $this->db->where("pendaftaran_mulai<=".strtotime("now"), NULL, FALSE);
        $this->db->where("pendaftaran_akhir>".strtotime("now"), NULL, FALSE);
        $this->db->where("tersedia", "1");
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        if($q!=NULL){
            $this->db->group_start();
            $this->db->like('id', $q);
            $this->db->or_like('posisi_jabatan', $q);
            $this->db->or_like('pendaftaran_mulai', $q);
            $this->db->or_like('pendaftaran_akhir', $q);
            $this->db->or_like('kode_bahan', $q);
            $this->db->or_like('kuota', $q);
            $this->db->or_like('kode_ujian', $q);
            $this->db->group_end();
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        if($q!=NULL){
            $this->db->group_start();
            $this->db->like('id', $q);
            $this->db->or_like('posisi_jabatan', $q);
            $this->db->or_like('pendaftaran_mulai', $q);
            $this->db->or_like('pendaftaran_akhir', $q);
            $this->db->or_like('kode_bahan', $q);
            $this->db->or_like('kuota', $q);
            $this->db->or_like('kode_ujian', $q);
            $this->db->group_end();
        }
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table."_overview")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data by spesific field
    function update_by($field, $val, $data)
    {
        $this->db->where($field, $val);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete data by spesific field
    function delete_by($field, $val)
    {
        $this->db->where($field, $val);
        $this->db->delete($this->table);
    }

}

/* End of file Pekerjaan_model.php */
/* Location: ./application/models/Pekerjaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-14 06:43:01 */
/* http://harviacode.com */